services:
  client:
    container_name: my_client_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./production.db
    volumes:
      - ./prisma/production.db:/app/prisma/production.db
